version: '3.8'

services:
  web:
    image: ghcr.io/cabralads/moravo:main
    restart: always
    environment:
      # O DATABASE_URL e o JWT_SECRET podem ser configurados nas variáveis de ambiente no Portainer
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 168
    volumes:
      - uploads_data:/app/uploads

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  uploads_data:
  caddy_data:
  caddy_config:
