version: '3.8'

services:
  web:
    image: ghcr.io/cabralads/moravo:main
    environment:
      # O DATABASE_URL e o JWT_SECRET são configurados no Portainer
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 168
    volumes:
      - uploads_data:/app/uploads
    networks:
      - traefik_public
      - digital_network
    dns:
      - 8.8.8.8
      - 1.1.1.1
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.http.routers.moravo.entrypoints: "web,websecure"
        traefik.http.routers.moravo.rule: "Host(`moravo.com.br`) || Host(`www.moravo.com.br`)"
        traefik.http.routers.moravo.tls.certresolver: "le"
        traefik.http.services.moravo.loadbalancer.passHostHeader: "true"
        traefik.http.services.moravo.loadbalancer.server.port: "3000"

volumes:
  uploads_data:

networks:
  traefik_public:
    external: true
  digital_network:
    external: true
